base_cfg: ./tasks/partnet_seg/configs/default/model.yaml
task:
  name: partnet_seg

dataset:
  name: baseline
  path: ./datas/partnet
  category: Chair
  level: 3

  prefps_path: ./datas/partnet/pre_sampler
  use_label_weights: False
  repeat_until_num: 2000

train:
  max_epochs: 150
  eval_epoch: 10

  optimizer: 
    name: sgd
    lr: 0.01
    lr_scheduler: 'multi-step'
    lr_decay_rate: 0.1
    lr_decay_list: [100, 150]
    lr_clip: 0.000001
    weight_decay: 0.001
  
  loss:
    name: baseline
  